services:
  userservice:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: userservice

    restart: always

    ports:
      - "3001:5179"

    environment:
      - ASPNETCORE_ENVIRONMENT=Production
