version: '3.8'

services:
  userservice:
    build:
      context: .
      dockerfile: UserService/Dockerfile

    container_name: userservice

    restart: always

    ports:
      - "3001:8080"

    env_file:
      - .env

    environment:
      - ASPNETCORE_ENVIRONMENT=Production
